### ISSUE TITLE
Feature Request: Waypoint like autogeneration of MOCs

### ISSUE THREAD

**Issue by JulianDicken** [dalcantara7/obsidian-auto-moc#11]
It would be great if there was a way to autogenerate MOCs in a document in a similar way to how Waypoint does it -- generating the MOCs from a waypoint like entry point should then be doable via a command. This would make maintaining tag MOCs much easier

If it already is possible like this somehow im sorry but I couldnt really tell from the documentation

**Comment by dalcantara7** [comment]
Just to clarify. Are you referring to this [Waypoint plugin](https://github.com/IdreesInc/Waypoint)?

If so, I'm not sure what the ask is here? Is it the live updating functionality? Or...? Could you give me an example use case?

**Comment by dalcantara7** [comment]
Closing this due to no response
