### ISSUE TITLE
Frontmatter tags

### ISSUE THREAD

**Issue by Mealso310** [dalcantara7/obsidian-auto-moc#12]
Hi, for me, it seems that frontmatter tags are not recognized, even if I can see them in the keywords panel in Obsidian, and if I wait a long time before submitting a request as you recommend.
Obsidian is updated and your plugin too.
What am I missing ?
Thanks for the job anyway

**Comment by dalcantara7** [comment]
Can you post an example of what your frontmatter looks like?

Also what do you mean you can see them in the "keywords panel"?

**Comment by Mealso310** [comment]
Hi, thanks for your quick reply

I have force reload Obsidian and waited  after added the tag « Atomoc"

Here are screenshots I hope they’ll explain my issue.



Thanks again
Marc

**Comment by dalcantara7** [comment]
Hi, I don't think the screenshots got included in the post. Could you please attach them?

Thanks

**Comment by dalcantara7** [comment]
Closing due to lack of response
