### ISSUE TITLE
Request for Option to Disable Notifications if No Links are Found

### ISSUE THREAD

**Issue by erauner12** [dalcantara7/obsidian-auto-moc#13]
Thank you for this excellent plugin. I've bound it to my linting action so that I can effortlessly connect notes together.

The reason I am requesting this is that since I am consistently running this command (linting/saving often), I am not interested in receiving a notification if there are no links found on this page.

ex:

<img width="173" alt="image" src="https://github.com/dalcantara7/obsidian-auto-moc/assets/59383957/31367ad9-eeb5-419b-a62a-61cad79a9771">

Could you please provide an option to disable these notifications if there are no links? I would still prefer to receive the notification if there is indeed something linked to the file when it runs.

**Comment by dalcantara7** [comment]
Hello,

I'm glad you're getting value from the plugin. This is a great feature suggestion. I have added it in release 1.3.3. Please update the plugin and let me know if you run into any problems. I will close this ticket for now
