### ISSUE TITLE
Feature Request: Find and link alias

### ISSUE THREAD

**Issue by harrislop** [dalcantara7/obsidian-auto-moc#14]
I'm using the plug-in that you made. I'm writing like this because I want to have one more function.

Currently, I understand that the function using alias only brings the links mentioned.

Is it possible to add a function to search for alias and import links like importing links through tags?

**Comment by dalcantara7** [comment]
Hello, sorry for the delay in responding. I think this is a good suggestion (thank you) and I have updated the plugin with support for this (release 1.3.4). Please update your plugin to get the new feature. If you encounter any bugs, feel free to reopen this ticket. Closing for now
