### ISSUE TITLE
[feature request] add links as a non numbered liat

### ISSUE THREAD

**Issue by danielo515** [dalcantara7/obsidian-auto-moc#15]
Hello, 👋 thanks for this plugin, I use it extensively.
I think it will be cool if you can choose links to be inserted as a non numbered list. Right now I'm doing it manually, and it will be a nice QOL improvement

**Comment by dalcantara7** [comment]
Hello and Happy New Year,

I think this is a great feature request. I have implemented the change in release 1.4.0. I also added support for ordered lists and checkbox lists. Just in case people want them. Please update the plugin and let me know here if you run into any issue. I will close this for now

**Comment by danielo515** [comment]
Thank you very much!
Happy new year to you too
