### ISSUE TITLE
Feature Request: Support for "Add missing notes multiple tags at the current cursor location"

### ISSUE THREAD

**Issue by victorcomposes** [dalcantara7/obsidian-auto-moc#16]
I'd like to be able to add multiple tags within the modal, instead of just one.

Option 1 (Comma Separated):

`#software-engineering, #wiki, #algorithms`

only the notes with tags stipulated above nothing else

Option 2 (Conditions):

`#software-engineering AND #wiki AND #algorithms AND !#random`
 
`AND` includes the tag,
`AND !#random` excludes notes with that specified tag

Your feedback would be much appreciated

**Comment by dalcantara7** [comment]
Hi, I agree this would be a very useful feature to implement. However, as far I can tell this type of action is not supported in the FuzzySuggestModal (or [any of the modals](https://docs.obsidian.md/Plugins/User+interface/Modals) for that matter)  I am using for tag selection. 
I don't have the technical know how to implement my own. I am going to mark this as "**wontfix**" but will keep it open in the event someone comes across this and knows how to fix it. I'm sorry I couldn't be of more help.

**Comment by dalcantara7** [comment]
Closing this issue to clean up a bit, but adding the "help wanted" label so that other can still see this an contribute if they know how
