### ISSUE TITLE
Feature Request: Add Option to Ignore Specified Folder Paths When Running AutoMOC Command

### ISSUE THREAD

**Issue by santiyounger** [dalcantara7/obsidian-auto-moc#17]
Thank you for this awesome plugin. I rely on it a lot.

I'm wondering if it'd be possible to add a feature where, in the settings of this plugin, I could determine a folder path to be ignored when running the AutoMOC command, so that any notes with a backlink to my main MOC can be excluded due to them being in a particular folder.

I use the Templator plugin by default to add a backlink to a central MOC note that I have, which means that all of my notes have a backlink to my main central MOC note. However, I realized that a really good workflow for me is moving notes into different folders to filter out those I don't want in my central MOC.

This folder workflow is better than manually removing default backlinks, because I can do this in batch, and I can have all sorts of systems to make it a bit easier.  
I'm wondering if it'd be possible to add such a feature.

Thanks

**Comment by dalcantara7** [comment]
Hi, so sorry for the delayed reply. I've been quite busy as of late. I think this is a great idea and I'll start working on an implementation. I will update you when it is up

**Comment by dalcantara7** [comment]
Hi, the implementation was simpler than I imagined and I have released the feature with release 1.5.0. Please test and make sure that it works properly. If you encounter any issues, let me know on this ticket. I will close it for now.
