### ISSUE TITLE
Feature Request: Link named as first Alias

### ISSUE THREAD

**Issue by naarcissus** [dalcantara7/obsidian-auto-moc#5]
I tend to name notes so that they have some sort of order to them when I browse them in my file manager, so they aren't really named well for inclusion in a list. So I use Aliases.
I would like to have the option to have each link printed as `[<file link>|<1st alias>]` so that they show up as `<first alias>`.

**Comment by naarcissus** [comment]
Working well. Thank you for adding it this.

**Comment by dalcantara7** [comment]
Just an FYI. The logic I was using to check for aliases was flawed. If you have a note with a frontmatter like the following:

```
---
aliases:
---
```

i.e. you allocate the aliases field, but don't provide any aliases,

the plugin will throw an error. I have updated the logic, but you may need to uninstall and reinstall the plugin to see the changes.
