### ISSUE TITLE
Feature Request: Sort list before inserting it

### ISSUE THREAD

**Issue by naarcissus** [dalcantara7/obsidian-auto-moc#6]
As it says in the title, I'd like to have the list inserted in alphabetical order so I don't have to cut then paste into Notepad++, sort lines lexicographically ascending, select all, cut, paste back into Obsidian.

Edit: I don't know what information you have access to…, but if you do implement this, it might be appropriate to be able to sort by other factors: note modification date, creation date, size (filesize, character count, word count). Just some ideas, I don't *need* any of those extras myself.

**Comment by dalcantara7** [comment]
Great suggestion! I have implemented alphabetical sort and it will be available in the next release. 

I'm going to hold off on the other sorts until I see some demand for them. Thanks again.

(I will close this once the release is available)

**Comment by dalcantara7** [comment]
The release has been published. You can update the plugin now.

**Comment by naarcissus** [comment]
Seems to work great! Thank you!
